Generate a friendly script ID
openflighthpc/flight-job pull request #47
Opened 2021-09-10 12:09 UTC by WilliamMcCumstie

Previously the `script_id` would be a random string, making it hard to track the scripts. Instead they are now generated off the `template` id:

* The first default is the `template_id`,
* The second default is `template_id-1`,
* `template_id-2`
* ...

The first available default will always be used. This means the `script_id` for a deleted script will be reused.

2021-09-10 13:59 UTC, benarmston commented
Regarding the id lengths.  We decided to restrict the length of script ids so that they took up a sensible amount of space in the `list-scripts` output.  (At one stage we used UUIDs which left very little room for anything else).  We didn't add validation to restrict the length of job ids as we were generating them with a fixed length.

With this change we no longer have a fixed length for job ids.  Validation of job id length should be added too (and handling of too long generated ids).

2021-09-13 15:25 UTC, WilliamMcCumstie commented
The friendly name generation now respects the maximum `id` length. It will start to truncate the base name when the length is exceeded:

```
long-template-99
long-templat-100
```

2021-09-27 12:43 UTC, benarmston commented
@WilliamMcCumstie can you rebase this on `master` please?

2021-09-28 15:09 UTC, WilliamMcCumstie commented
Rebased on master

2021-09-30 15:02 UTC, benarmston requested changes
I've pushed some commits to address some issues.  I also have a couple of questions for you to look at.

The main issue was a bad configuration could break job submission without it being obvious why.  Now it breaks flight job entirely, but in an obvious way.

The second issues was to do with sorting the scripts.  Below are two screenshots the second is the sort order that we have now.

![image](https://user-images.githubusercontent.com/287050/135479697-f9967e19-4595-4e3c-a3db-949aa201e422.png)


![image](https://user-images.githubusercontent.com/287050/135479758-a12d9d2e-cf4c-4823-b035-1a31946b020f.png)


The sort order isn't perfect as the next screenshot shows.  I can live with this though.

![image](https://user-images.githubusercontent.com/287050/135480703-df0e0cde-5269-4877-8a45-c42a6eea8466.png)

2021-10-01 15:11 UTC, WilliamMcCumstie commented on lib/flight_job/models/script.rb
> +        rescue
You raise a good point

e616eb1ff7376961607e171b496a7d02af675cb9

2021-10-01 15:12 UTC, WilliamMcCumstie commented on lib/flight_job/models/script.rb
> +        YAML.load File.read(metadata_path)
Yes, this is still true for the `Script` model. It would not be true for the `Job` model.

2021-10-04 11:09 UTC, benarmston commented on lib/flight_job/models/script.rb
> +        YAML.load File.read(metadata_path)
Thanks for the clarification.  I must have confused myself on what class I was looking at.

2021-10-04 11:31 UTC, benarmston commented
I've merged `master` into this branch as it seemed *much* simpler than trying to rebase on top of `master`.  LGTM.

2021-10-04 11:31 UTC, merged